language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: false
      mono: latest
      dotnet: 2.1.300
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.1.300
      mono: latest
      sudo: false

install:
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

script: 
  - dotnet --info
  - ./build.sh All

branches:
  except:
    - gh-pages