language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: false
      mono: latest
      dotnet: 3.0.100
    - os: osx 
      osx_image: xcode9.3 # OSX 10.13 https://docs.travis-ci.com/user/reference/osx/#using-macos
      dotnet: 3.0.100
      mono: latest
      sudo: false

install:
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

script: 
  - dotnet --info
  - ./build.sh All

branches:
  except:
    - gh-pages
