language: generic

matrix:
  include:
    - language: csharp
      os: osx
      osx_image: xcode9.3 # OSX 10.13 https://docs.travis-ci.com/user/reference/osx/#using-macos
      dotnet: 3.1.301
      mono: latest
      install:
        # workaround for missing .net 4.5 targing pack
        - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
      script: 
        - dotnet --info
        - ./build.sh All
      branches:
        except:
          - gh-pages
    - language: csharp
      os: linux 
      dist: xenial # Ubuntu 16.04 https://docs.travis-ci.com/user/reference/linux/
      mono: latest
      dotnet: 3.1.301
      install:
        # workaround for missing .net 4.5 targing pack
        - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
      script: 
        - dotnet --info
        - ./build.sh All
      branches:
        except:
          - gh-pages

    - language: node_js
      os: osx
      osx_image: xcode9.3 # OSX 10.13 https://docs.travis-ci.com/user/reference/osx/#using-macos
      dotnet: 3.1.301
      mono: latest
      node_js: 14
      cache: yarn
      install:
        # workaround for missing .net 4.5 targing pack
        - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
      before_script:
        - cd tests/fable
      script:
        - dotnet --info
        - ./build.sh Build
        - yarn test
      branches:
        except:
          - gh-pages
    - language: node_js
      os: linux 
      dist: xenial # Ubuntu 16.04 https://docs.travis-ci.com/user/reference/linux/
      mono: latest
      dotnet: 3.1.301
      node_js: 14
      cache: yarn
      install:
        # workaround for missing .net 4.5 targing pack
        - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
      before_script:
        - dotnet --info
        - ./build.sh Build
        - cd tests/fable
      script:
        - yarn test
      branches:
        except:
          - gh-pages
