environment:
  CLI_VERSION: 3.0.100
image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
