environment:
  CLI_VERSION: 3.1.301
image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 14
  - yarn --cwd tests/fable --cache-folder=.cache/yarn --no-progress --pure-lockfile
cache:
  - tests/fable/.cache/yarn
build_script:
  - cmd: build.cmd
test: off
test_script:
  - yarn --cwd tests/fable test
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
