name: Build and Test Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202'
    - name: Install tools
      run: dotnet tool restore
    - name: Build Test and Docs using FAKE 
      run: dotnet fake build
